### ISSUE TITLE
When i trying gpt-3.5-turbo-instruct it cause the error, is it possible to use this model?

### ISSUE THREAD

**Issue by vadykoo** [smikitky/chatgpt-md-translator#11]
Translating: /Users/user/Desktop/PRO/projects/docs/hashing.md
Model: gpt-3.5-turbo-instruct, Temperature: 0.1 

⚡ [⚡, ❌ This is not a chat model and thus not supported in the v1/chat/completions endpoint. Did you mean to use v1/completions?]
Error This is not a chat model and thus not supported in the v1/chat/completions endpoint. Did you mean to use v1/completions?
    at translateOne (file:///usr/local/lib/node_modules/chatgpt-md-translator/lib/translate.js:17:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 1)
    at async translateMultiple (file:///usr/local/lib/node_modules/chatgpt-md-translator/lib/translate.js:34:21)
    at async main (file:///usr/local/lib/node_modules/chatgpt-md-translator/lib/index.js:51:28)

**Comment by smikitky** [comment]
No, you cannot use gpt-3.5-turbo-*instruct* because it's not a chat model, as the error message says. Please just use gpt-3.5-turbo.

It's technically possible to use this model after modifying some code, but I doubt it's very beneficial to do so...

**Comment by vadykoo** [comment]
Thanks 👍
